# Generated by Django 5.1.1 on 2024-09-27 00:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_public', models.CharField(max_length=200)),
                ('resumen_public', models.TextField()),
                ('contenido_public', models.TextField(blank=True)),
                ('fecha_creacion_public', models.DateTimeField(default=datetime.datetime(2024, 9, 27, 0, 37, 35, 996594, tzinfo=datetime.timezone.utc))),
                ('fecha_publicacon', models.DateField(blank=True, null=True)),
                ('imagen_public', models.ImageField(blank=True, height_field=300, help_text='selecciona una imagen para la publicación', null=True, upload_to='media', width_field=500)),
                ('autor_public', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categorias', models.ManyToManyField(related_name='Publicacion', to='publicaciones.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_comentario', models.TextField()),
                ('fecha_comentario', models.DateTimeField(default=datetime.datetime(2024, 9, 27, 0, 37, 35, 997597, tzinfo=datetime.timezone.utc))),
                ('aprobado', models.BooleanField(default=False)),
                ('autor_comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='publicaciones.publicacion')),
            ],
        ),
    ]
