# Generated by Django 5.1.1 on 2024-10-12 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0010_alter_comentario_fecha_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha_comentario',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 12, 13, 27, 57, 869674, tzinfo=datetime.timezone.utc)),
        ),
    ]
