# Generated by Django 5.1.1 on 2024-10-12 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0011_alter_comentario_fecha_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha_comentario',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 12, 23, 26, 49, 853903, tzinfo=datetime.timezone.utc)),
        ),
    ]
