# Generated by Django 5.1.1 on 2024-10-13 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0012_alter_comentario_fecha_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha_comentario',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 13, 21, 57, 24, 136672, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen_public',
            field=models.ImageField(blank=True, help_text='selecciona una imagen para la publicación', null=True, upload_to='img/'),
        ),
    ]
