# Generated by Django 5.1.1 on 2024-10-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0014_alter_comentario_fecha_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='imagen_public',
            field=models.ImageField(blank=True, help_text='selecciona una imagen para la publicación', null=True, upload_to='image/'),
        ),
    ]
